### GET users
GET localhost:8080/api/users/
Accept: application/json

### GET user by ID
GET localhost:8080/api/users/2
Accept: application/json

### Create user
POST localhost:8080/api/register
Content-Type: application/json

{
  "fullName": "Serikov Dias",
  "login": "qara-qurt12",
  "password": "qwerty"
}

### Delete user by ID
DELETE localhost:8080/api/users/2

### Update user
PATCH localhost:8080/api/users/3
Content-Type: application/json

{
  "fullName": "tima",
  "login": "qara-qurt",
  "password": "dias"
}

### Change password
PATCH localhost:8080/api/users/change-password
Content-Type: application/json

{
  "login": "qara-qurt12",
  "currentPassword": "dias",
  "newPassword": "diass"
}
